### ISSUE TITLE
EFT overflows

### ISSUE THREAD

**Issue by munrocket** [JuliaMath/AccurateArithmetic.jl#8]
@JeffreySarnoff in one rust package https://docs.rs/safeeft/0.0.5/safeeft/ I found new safe EFT.
They said that M.Kashiwagi in his paper (in japanese) found special cases where twoSum and twoProducts not safe enough with IEEE 747-2008 floats. What do you think about that?
```
twosum ( 3 . 5 6 3 0 6 2 4 4 4 4 8 7 4 5 3 9 e +307 ,
−1 .7976931348623157 e +308)
( −1 .4413868904135704 e +308 , nan )
twoproduct ( 6 . 9 2 9 0 0 1 7 1 3 8 6 9 9 3 6 e +236 ,
2 . 5 9 4 4 4 7 5 2 5 1 9 5 2 0 0 3 e+71)
( 1 . 7 9 7 6 9 3 1 3 4 8 6 2 3 1 5 7 e +308 , i n f )
```

**Comment by dpsanders** [comment]
This is very interesting and exactly what we need for IntervalArithmetic.jl.

What is the license on that package? Would you like to port it to Julia?

**Comment by dpsanders** [comment]
This seems to be the repo, with MIT license!

https://github.com/GNQG/safeeft

**Comment by munrocket** [comment]
Actually good old EFT just works in most of the cases, especially for usage in graphics. It is possible that nobody found this problem since 1970? Just curious.

**Comment by JeffreySarnoff** [comment]
I am aware of these outlier cases.  I will take a look at the repo code and opine.

**Comment by JeffreySarnoff** [comment]
AccurateArithmetic.jl is no longer current (though I try).  The best code for eft stuff is ErrorfreeArithmetic.jl in my github space.

**Comment by munrocket** [comment]
Sorry, probably opened issue in wrong place.

**Comment by JeffreySarnoff** [comment]
`safetwosum_branch` from the rust repo is < 20% slower than `two_sum`, the straight line version is much more time consuming.


- [ ]

**Comment by JeffreySarnoff** [comment]
`safetwoproduct_fma` from the rust repo is the same as `two_prod`.
So I could easily add a `safe_two_sum` that uses the branch logic.
@dpsanders does this work for you?

**Comment by JeffreySarnoff** [comment]
oic (in the paper) there are also versions of add, sqrt, mul, div that round up and versions round down

**Comment by JeffreySarnoff** [comment]
read too quickly (my Japanese is rusty at best [google translate is difficult to read because there are overlapping sections in the translation]. https://translate.google.com/translate?hl=en&sl=ja&u=http://verifiedby.me/adiary/pub/kashi/image/201406/nas2014.pdf&prev=search

The rounded-up and rounded-down routines are intended to deliver Float64 results using two_xxx routines internally.  They do work correctly for that @dpsanders they use pretty much the same approach we have used in `FastRounding`.  I could play with recoding that for you. after New Years

**Comment by dpsanders** [comment]
That sounds great. I don't read Japanese but may be able to get some help with that.

**Comment by munrocket** [comment]
In Julia you also have emulated [fma](https://github.com/JuliaMath/openlibm/blob/master/src/s_fma.c) instruction with EFT too.

**Comment by JeffreySarnoff** [comment]
yes .. however hardware `fma` for Float64 and Float32 is widespread, so much so that all of `DoubleFloats` is built upon the presumption of its presence [and there have been no issues with that decision].  The additional time required absent hardware `fma` is so great that to require that implementation is to remove one of the essential qualities that others find worthwhile in the pkg.

**Comment by munrocket** [comment]
So... This is just an overflow problem. If some value overflows, we can say that result become unexpected, that’s all.

**Comment by munrocket** [comment]
Also this Kashiwagi paper is cool, but without formal proof.

**Comment by JeffreySarnoff** [comment]
@munrocket Now ErrorfreeTransformations.jl `three_fma` (and new, `two_fma`) should work alright -- let me know if they do not.  If you find they work, I will move the changes here too.

**Comment by munrocket** [comment]
Probably I need to close the issue because it’s become clear what they calculate in rust packages. I think that we need more cites or/and formal proves to trust a new papers. Also we need to know when we need safe overflows and how often they occur.

**Comment by munsocket** [comment]
Found an error in paper here
```python
def succ (x) :
  if (a < 2.**(−1021)):
    return x + a * 2.**(−1074) //<--
```

**Comment by JeffreySarnoff** [comment]
You found an error in what paper? and what should it read?

**Comment by munsocket** [comment]
I am used successor()/predecessor() from M.Kashiwagi paper it and found an error in this test.
```js
succ(2e-300) === 2.0000000000000004e-300
```
I am just reporting that this paper have some bugs. I am able to fix it. But anyway it feels little bit strange.
```python
return x + 2.**(−1074) //<--fixed
```

**Comment by JeffreySarnoff** [comment]
what does that return statement read in the paper? do you have a link to this paper?

**Comment by JeffreySarnoff** [comment]
If you have not seen this paper [Computing predecessor and successor in rounding to nearest](http://www.ti3.tuhh.de/paper/rump/RuZiBoMe08.pdf).

**Comment by munsocket** [comment]
Yea, this technique is described in “Computing predecessor and successor in rounding to nearest”, but it doesn’t have any source code, so I am used paper from Kashiwagi
https://translate.google.com/translate?hl=en&sl=ja&u=http://verifiedby.me/adiary/pub/kashi/image/201406/nas2014.pdf&prev=search
I am just warned you about bugs. They can be in another functions too, seems that code not properly tested.

**Comment by munsocket** [comment]
If you know some other paper about safe EFT and correctness of algorithms, I will appreciate.

**Comment by JeffreySarnoff** [comment]
Yes -- I know that paper and it has glitches.

[Double-Double Building Blocks]
M. Joldes, V. Popescu, and J.M. Muller.
Tight and rigourous error bounds for basic building blocks of double-word arithmetic
2016, working paper.
https://hal.archives-ouvertes.fr/hal-01351529v2/document

[Triple-Double Building Blocks]
Christoph Quirin Lauter.
Basic building blocks for a triple-double intermediate format
2005, research report.
https://hal.inria.fr/inria-00070314/document

**Comment by munsocket** [comment]
thanks!
