### ISSUE TITLE
Requesting a new release

### ISSUE THREAD

**Issue by helgee** [JuliaMath/AccurateArithmetic.jl#9]
Thanks for the package! A new release would be much appreciated 👍

Many thanks in advance!

**Comment by JeffreySarnoff** [comment]
Please use https://github.com/JeffreySarnoff/ErrorfreeArithmetic.jl -- it is more current and whatever I do with this pkg will be copied from that.

**Comment by JeffreySarnoff** [comment]
I did just add a release.

**Comment by JeffreySarnoff** [comment]
well, trying to rerelease

**Comment by JeffreySarnoff** [comment]
done

**Comment by JeffreySarnoff** [comment]
umm -- inadvertantly, I mislead you about this pkg.
It was rewritten by the authors of https://hal.archives-ouvertes.fr/hal-02265534v2/document
So if your intent is to use the compensated routines -- have it, they are quite good.

**Comment by helgee** [comment]
> umm -- inadvertently, I mislead you about this pkg.
> It was largely rewritten by the authors of https://hal.archives-ouvertes.fr/hal-02265534v2/document
> So if your intent is to use the compensated routines -- have it, they are quite good.

No matter. I am specifically interested in the `dot_oro` method in the package. Thanks for releasing a new version 👍
